(() => {
  'use strict';
  const $ = s => document.querySelector(s);
  const workflow = MadarWorkflow;
  const stages = workflow.groups.map(g=>({id:g.id,name:g.name,color:g.color}));
  const priorities = {high:'بالا',medium:'متوسط',low:'پایین'};
  const KEY = 'madar.workspace.v1';
  const uid = () => crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2);
  const seed = () => ({version:1,projects:[{id:uid(),name:'حساب‌یار',description:'پروژه شما؛ توضیحات، مرحله توسعه و کارها را مطابق وضعیت واقعی ویرایش کنید.',stage:'idea',priority:'medium',color:'#6789c2',tech:[],repo:'',url:'',deadline:'',tasks:[],activity:[],updated:new Date().toISOString()}]});
  let state, view='dashboard', filter='all', query='', editing=null, activeProject=null;
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num = v => Number(v).toLocaleString('fa-IR');
  const stage = p => stages.find(s=>s.id===p.stage) || stages[0];
  const progress = p => {const s=workflow.summary(p);return s.total+p.tasks.length?Math.round((s.done+p.tasks.filter(t=>t.done).length)/(s.total+p.tasks.length)*100):0};
  const safeURL = v => {try {const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
  const date = v => v ? new Date(v.length===10?v+'T12:00:00':v).toLocaleDateString('fa-IR',{month:'short',day:'numeric'}) : 'بدون تاریخ هدف';
  function valid(s) {return s && s.version===1 && Array.isArray(s.projects) && s.projects.length<=1000 && s.projects.every(p=>p && typeof p.id==='string' && typeof p.name==='string' && p.name.trim() && p.name.length<=80 && typeof p.description==='string' && (stages.some(x=>x.id===p.stage)||Object.hasOwn(workflow.legacy,p.stage)) && workflow.valid(p.checklist) && Object.hasOwn(priorities,p.priority) && /^#[\da-f]{6}$/i.test(p.color) && Array.isArray(p.tech) && p.tech.every(x=>typeof x==='string') && typeof p.repo==='string' && typeof p.url==='string' && typeof p.deadline==='string' && (!p.deadline || /^\d{4}-\d{2}-\d{2}$/.test(p.deadline)) && Array.isArray(p.tasks) && p.tasks.every(t=>t && typeof t.id==='string' && typeof t.title==='string' && typeof t.done==='boolean') && Array.isArray(p.activity) && p.activity.every(a=>a && typeof a.text==='string' && typeof a.at==='string') && typeof p.updated==='string') && new Set(s.projects.map(p=>p.id)).size===s.projects.length;}
  try {const raw=localStorage.getItem(KEY);state=raw?JSON.parse(raw):seed();if(!valid(state))throw Error('invalid')}catch{state=seed();setTimeout(()=>toast('اطلاعات قبلی خوانده نشد؛ قبل از ذخیره، نسخه پشتیبان را بررسی کنید.'),500)}
  state.projects.forEach(p=>workflow.migrate(p));
  function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('.local-badge').innerHTML='<i></i> ذخیره خودکار فعال';return true}catch{$('.local-badge').textContent='ذخیره انجام نشد';toast('فضای ذخیره مرورگر در دسترس نیست؛ نسخه پشتیبان بگیرید.');return false}}
  function log(p,text){p.updated=new Date().toISOString();p.activity.unshift({text,at:p.updated});p.activity=p.activity.slice(0,30)}
  function update(){save();render();if(activeProject && $('#detail-dialog').open)renderDetail()}
  $('#today').textContent=new Date().toLocaleDateString('fa-IR',{weekday:'long',day:'numeric',month:'long'});
  $('select[name=stage]').innerHTML=stages.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');
  function render(){
    const total=state.projects.length, allTasks=state.projects.flatMap(p=>p.tasks), done=allTasks.filter(t=>t.done).length;
    $('#nav-count').textContent=num(total);$('.workspace small').textContent=`${num(total)} پروژه، یک مسیر روشن`;
    $('#stats').innerHTML=[['همه پروژه‌ها',total,'▣','ایده‌هایی که می‌سازی'],['در حال توسعه',state.projects.filter(p=>p.stage==='preparation').length,'⌘','در مسیر تبدیل شدن به محصول'],['منتشر شده',state.projects.filter(p=>p.checklist['publication.publish'].status==='done').length,'↗','آماده استفاده کاربران'],['کارهای تکمیل‌شده',done,'✓',`از ${num(allTasks.length)} کار ثبت‌شده`]].map(x=>`<div class="stat"><div class="stat-top"><span>${x[0]}</span><span class="stat-icon">${x[2]}</span></div><div class="stat-value">${num(x[1])}</div><div class="stat-bottom">${x[3]}</div></div>`).join('');
    $('#pipeline-bars').innerHTML=stages.map(s=>{const count=state.projects.filter(p=>p.stage===s.id).length;return `<div class="pipeline-row"><span>${s.name}</span><div class="bar"><div style="width:${total?count/total*100:0}%;background:${s.color}"></div></div><b>${num(count)}</b></div>`}).join('');
    const titles={dashboard:['همه پروژه‌ها، در یک مدار','تصویر روشنی از مسیر توسعه‌ات داشته باش؛ از اولین ایده تا آخرین انتشار.','نمای کلی'],projects:['ایده‌های تو، پروژه‌های فردا','تمام پروژه‌ها و مراحل توسعه را از اینجا مدیریت کن.','پروژه‌ها'],tasks:['هر کار، یک قدم رو به جلو','کارهای پروژه‌هایت را ثبت کن و پیشرفت را ببین.','کارهای من'],releases:['آماده برای دنیا','دامنه، مخزن کد و وضعیت انتشار پروژه‌هایت در یک جا.','انتشار و دامنه‌ها']};
    $('#page-title').textContent=titles[view][0]+'.';$('#page-description').textContent=titles[view][1];$('#breadcrumb-title').textContent=titles[view][2];
    $('#overview').hidden=view!=='dashboard';$('#stats').hidden=view==='tasks'||view==='releases';$('.view-switch').hidden=view==='tasks'||view==='releases';$('#filters').hidden=view==='tasks'||view==='releases';
    $('#section-title').innerHTML= `${view==='tasks'?'کارهای پروژه‌ها':view==='releases'?'پروژه‌ها و آدرس انتشار':'پروژه‌های شما'} <span>${num(total)}</span>`;
    $('#section-description').textContent=view==='tasks'?'برای ثبت کار جدید، پروژه را باز کن.':view==='releases'?'آدرس‌ها از بخش ویرایش پروژه قابل ثبت هستند.':'جایی برای پیگیری ایده‌هایی که در حال ساختنشان هستی.';
    $('#filters').innerHTML=[{id:'all',name:'همه پروژه‌ها'},...stages].map(s=>`<button class="${filter===s.id?'selected':''}" data-filter="${s.id}">${s.name}</button>`).join('');
    let projects=state.projects.filter(p=>(filter==='all'||p.stage===filter||['tasks','releases'].includes(view)) && `${p.name} ${p.description} ${p.tech.join(' ')}`.toLocaleLowerCase().includes(query));
    $('#project-grid').hidden=['tasks','releases'].includes(view);$('#task-list').hidden=view!=='tasks';$('#release-list').hidden=view!=='releases';
    const empty='<div class="empty">موردی پیدا نشد. یک پروژه جدید اضافه کن یا جستجو را تغییر بده.</div>';
    $('#project-grid').innerHTML=projects.map(p=>`<article class="project-card" tabindex="0" role="button" aria-label="باز کردن پروژه ${esc(p.name)}" data-project="${esc(p.id)}" style="--project-color:${p.color};--stage-color:${stage(p).color}"><div class="card-top"><div class="project-icon">${esc(p.name.trim().slice(0,1))}</div><span class="status">${stage(p).name}</span></div><div><h3>${esc(p.name)}</h3><p class="card-description">${esc(p.description||'برای این پروژه توضیحات ثبت کن.')}</p></div><div class="tags">${p.tech.slice(0,4).map(t=>`<span>${esc(t)}</span>`).join('')}</div><div><div class="progress-label"><span>پیشرفت پروژه</span><b>${num(progress(p))}٪</b></div><div class="progress-track"><div style="width:${progress(p)}%"></div></div></div><div class="card-bottom"><span class="priority"><i></i>اولویت ${priorities[p.priority]}</span><span class="task-count">☑ ${num(p.tasks.filter(t=>t.done).length)} / ${num(p.tasks.length)}</span><span>${date(p.deadline)}</span></div></article>`).join('')||empty;
    $('#task-list').innerHTML=projects.map(p=>`<div class="task-group"><div class="section-top"><h3>${esc(p.name)}</h3><button class="secondary" data-project="${esc(p.id)}">＋ ثبت کار</button></div>${p.tasks.length?p.tasks.map(t=>taskHTML(p,t)).join(''):'<p>هنوز کاری ثبت نشده است.</p>'}</div>`).join('')||empty;
    $('#release-list').innerHTML=projects.map(p=>`<div class="release-card"><div><h3>${esc(p.name)} <span class="status" style="--stage-color:${stage(p).color}">${stage(p).name}</span></h3>${safeURL(p.url)?`<a href="${esc(safeURL(p.url))}" target="_blank" rel="noopener noreferrer" dir="ltr">${esc(p.url)} ↗</a>`:'<p>هنوز آدرس انتشار ثبت نشده</p>'}${safeURL(p.repo)?`<p><a href="${esc(safeURL(p.repo))}" target="_blank" rel="noopener noreferrer">مخزن کد ↗</a></p>`:''}</div><button data-project="${esc(p.id)}">مدیریت پروژه ←</button></div>`).join('')||empty;
  }
  function workflowHTML(p){
    const summary=workflow.summary(p);
    return '<section class="workflow"><div class="workflow-heading"><h3>چک‌لیست توسعه و انتشار</h3><strong>'+num(summary.percent)+'٪</strong></div><p class="workflow-intro">'+num(summary.done)+' از '+num(summary.total)+' مورد تکمیل شده · '+num(summary.skipped)+' مورد نیاز نیست. اطلاعات هر مورد را در یادداشت آن ثبت کن.</p><div class="workflow-summary-bar"><div style="width:'+summary.percent+'%"></div></div><div class="release-route" dir="ltr">Build Release → Upload → اطلاعات مارکت → ارسال برای بررسی → انتشار</div>'+workflow.groups.map(g=>{
      const s=workflow.summary(p,g.id);
      return '<details class="workflow-group" data-workflow-group="'+g.id+'" '+(g.id===p.stage?'open':'')+'><summary>'+g.name+'<small>'+num(s.done)+' / '+num(s.total)+(s.skipped?' · '+num(s.skipped)+' نیاز نیست':'')+'</small></summary><div class="workflow-body">'+(g.optional?'<p class="workflow-notice">اگر اپ پولی یا درآمدی است، موارد مربوط را تکمیل کن.</p><button class="workflow-skip" data-skip-group="'+g.id+'">این اپ درآمدی نیست</button>':'')+(g.id==='preparation'?'<p class="workflow-notice">برای امضا فقط وضعیت یا توضیح ثبت کن؛ فایل Keystore و رمز آن را اینجا وارد نکن.</p>':'')+workflow.entries.filter(x=>x.group===g.id).map(x=>{
        const v=p.checklist[x.id];
        return '<div class="workflow-item '+v.status+'"><div class="workflow-item-line"><label><input type="checkbox" data-checklist="'+x.id+'" '+(v.status==='done'?'checked':'')+' '+(v.status==='na'?'disabled':'')+'><span>'+esc(x.title)+'</span></label>'+(x.optional?'<select data-applicability="'+x.id+'" aria-label="نیاز به '+esc(x.title)+'"><option value="required" '+(v.status!=='na'?'selected':'')+'>نیاز دارد</option><option value="na" '+(v.status==='na'?'selected':'')+'>نیاز نیست</option></select>':'')+'</div><textarea class="workflow-note" rows="1" maxlength="2000" data-checklist-note="'+x.id+'" aria-label="یادداشت '+esc(x.title)+'" placeholder="اطلاعات، نتیجه تست یا لینک مرتبط…">'+esc(v.note)+'</textarea></div>';
      }).join('')+'</div></details>';
    }).join('')+'</section>';
  }
  function checklistUpdate(p){const open=Array.from(document.querySelectorAll('.workflow-group[open]')).map(x=>x.dataset.workflowGroup);update();for(const id of open){const node=document.querySelector('[data-workflow-group="'+id+'"]');if(node)node.open=true}}
  function taskHTML(p,t){return `<div class="task-row ${t.done?'done':''}"><input aria-label="تکمیل ${esc(t.title)}" type="checkbox" ${t.done?'checked':''} data-task="${esc(t.id)}" data-owner="${esc(p.id)}"><span class="task-title">${esc(t.title)}</span><button class="task-delete" title="حذف کار" data-delete-task="${esc(t.id)}" data-owner="${esc(p.id)}">×</button></div>`}
  function openForm(id=null){editing=id;const p=state.projects.find(x=>x.id===id),f=$('#project-form');f.reset();$('#form-title').textContent=p?'ویرایش پروژه':'پروژه جدید';for(const name of ['name','description','stage','priority','color','deadline','repo','url','tech'])if(p)f.elements[name].value=name==='tech'?p.tech.join(', '):p[name];$('#project-dialog').showModal()}
  function openDetail(id){activeProject=id;renderDetail();$('#detail-dialog').showModal()}
  function renderDetail(){const p=state.projects.find(x=>x.id===activeProject);if(!p)return;$('#detail-content').innerHTML=`<div class="modal-heading"><div><span class="eyebrow">جزئیات پروژه</span><h2>${esc(p.name)}</h2></div><button class="icon-button" data-close>×</button></div><p class="detail-description">${esc(p.description||'توضیحاتی ثبت نشده است.')}</p><div class="detail-meta"><span class="status" style="--stage-color:${stage(p).color}">اولویت ${priorities[p.priority]}</span><span class="status" style="--stage-color:#789362">هدف: ${date(p.deadline)}</span></div><div class="detail-stage">${stages.map(s=>`<button class="${s.id===p.stage?'selected':''}" data-stage="${s.id}">${s.name}</button>`).join('')}</div><div class="tags">${p.tech.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="progress-label"><span>پیشرفت پروژه و چک‌لیست</span><b>${num(progress(p))}٪</b></div><div class="progress-track" style="--project-color:${p.color}"><div style="width:${progress(p)}%"></div></div>${workflowHTML(p)}<section class="detail-tasks"><h3>کارها <small>(${num(p.tasks.length)})</small></h3>${p.tasks.map(t=>taskHTML(p,t)).join('')||'<p>اولین کار این پروژه را ثبت کن.</p>'}<form id="task-form" class="task-add"><input name="title" required maxlength="180" placeholder="کار بعدی چیست؟" aria-label="عنوان کار جدید"><button class="primary" type="submit">＋ افزودن</button></form></section><div class="detail-links">${safeURL(p.repo)?`<a href="${esc(safeURL(p.repo))}" target="_blank" rel="noopener noreferrer">مخزن کد ↗</a>`:''}${safeURL(p.url)?`<a href="${esc(safeURL(p.url))}" target="_blank" rel="noopener noreferrer">مشاهده اپ ↗</a>`:''}</div><div class="activity"><h3>تاریخچه فعالیت</h3>${p.activity.slice(0,6).map(a=>`<p>${esc(a.text)} · ${date(a.at)}</p>`).join('')||'<p>فعالیت‌های جدید اینجا ثبت می‌شوند.</p>'}</div><div class="detail-bottom"><button class="secondary" id="edit-project">ویرایش اطلاعات</button><button class="danger" id="delete-project">حذف پروژه</button></div>`;}
  document.addEventListener('click',e=>{const b=e.target.closest('button,[data-project]');if(!b)return;if(b.dataset.skipGroup){const p=state.projects.find(x=>x.id===activeProject);if(!p)return;for(const item of workflow.entries.filter(x=>x.group===b.dataset.skipGroup&&x.optional))p.checklist[item.id].status='na';log(p,'بخش درآمد: این اپ درآمدی نیست');checklistUpdate(p)}else if(b.dataset.view){view=b.dataset.view;filter='all';document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));render()}else if(b.dataset.filter){filter=b.dataset.filter;render()}else if(b.dataset.project){openDetail(b.dataset.project)}else if(b.hasAttribute('data-close')){b.closest('dialog').close()}else if(b.dataset.stage){const p=state.projects.find(x=>x.id===activeProject);p.stage=b.dataset.stage;log(p,`مرحله توسعه به «${stage(p).name}» تغییر کرد`);update()}else if(b.dataset.deleteTask){const p=state.projects.find(x=>x.id===b.dataset.owner);const t=p.tasks.find(x=>x.id===b.dataset.deleteTask);if(confirm(`کار «${t.title}» حذف شود؟`)){p.tasks=p.tasks.filter(x=>x.id!==t.id);log(p,`کار «${t.title}» حذف شد`);update()}}});
  document.addEventListener('change',e=>{
    const d=e.target.dataset, p=state.projects.find(x=>x.id===activeProject);
    if(d.checklist&&p){const item=workflow.entry(d.checklist);p.checklist[item.id].status=e.target.checked?'done':'pending';log(p,(e.target.checked?'تکمیل: ':'بازگشایی: ')+item.title);checklistUpdate(p);return}
    if(d.applicability&&p){const item=workflow.entry(d.applicability);if(!item?.optional)return;p.checklist[item.id].status=e.target.value==='na'?'na':'pending';log(p,item.title+' — '+(e.target.value==='na'?'نیاز نیست':'نیاز دارد'));checklistUpdate(p);return}
    if(e.target.dataset.task){const p=state.projects.find(x=>x.id===e.target.dataset.owner),t=p.tasks.find(x=>x.id===e.target.dataset.task);t.done=e.target.checked;log(p,`${t.done?'تکمیل':'بازگشایی'} کار «${t.title}»`);update()}});
  document.addEventListener('input',e=>{const id=e.target.dataset.checklistNote;if(!id)return;const p=state.projects.find(x=>x.id===activeProject);if(p&&workflow.entry(id)){p.checklist[id].note=e.target.value.slice(0,2000);p.updated=new Date().toISOString();save()}});
  document.addEventListener('keydown',e=>{if(e.target.matches('.project-card')&&['Enter',' '].includes(e.key)){e.preventDefault();openDetail(e.target.dataset.project)}if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('#search').focus()}});
  $('#add-project').onclick=()=>openForm();$('#tip-add').onclick=()=>openForm();$('#focus-tasks').onclick=()=>document.querySelector('[data-view=tasks]').click();
  $('#search').oninput=e=>{query=e.target.value.trim().toLocaleLowerCase();render()};$('#search').onkeydown=e=>{if(e.key==='Escape'){e.target.value='';query='';render()}};
  $('#grid-view').onclick=()=>{$('#project-grid').classList.remove('list');$('#grid-view').classList.add('selected');$('#list-view').classList.remove('selected')};$('#list-view').onclick=()=>{$('#project-grid').classList.add('list');$('#list-view').classList.add('selected');$('#grid-view').classList.remove('selected')};
  $('#project-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);const name=data.get('name').trim();if(!name){toast('نام پروژه را وارد کنید.');return}const fields={name,description:data.get('description').trim(),stage:data.get('stage'),priority:data.get('priority'),color:data.get('color'),deadline:data.get('deadline'),repo:data.get('repo').trim(),url:data.get('url').trim(),tech:data.get('tech').split(/[,،]/).map(t=>t.trim()).filter(Boolean)};if((fields.repo&&!safeURL(fields.repo))||(fields.url&&!safeURL(fields.url))){toast('آدرس‌ها باید با https:// یا http:// شروع شوند.');return}let p=state.projects.find(x=>x.id===editing);if(p){Object.assign(p,fields);log(p,'اطلاعات پروژه ویرایش شد')}else{p={id:uid(),...fields,checklist:workflow.blank(),tasks:[],activity:[],updated:new Date().toISOString()};log(p,'پروژه ایجاد شد');state.projects.unshift(p)}save();$('#project-dialog').close();render();toast('پروژه ذخیره شد.')};
  $('#detail-content').addEventListener('submit',e=>{if(e.target.id!=='task-form')return;e.preventDefault();const title=e.target.elements.title.value.trim();if(!title)return;const p=state.projects.find(x=>x.id===activeProject);p.tasks.push({id:uid(),title,done:false});log(p,`کار «${title}» اضافه شد`);update();$('#task-form input').focus()});
  $('#detail-content').addEventListener('click',e=>{if(e.target.id==='edit-project'){$('#detail-dialog').close();openForm(activeProject)}if(e.target.id==='delete-project'){const p=state.projects.find(x=>x.id===activeProject);if(confirm(`پروژه «${p.name}» و تمام کارهای آن حذف شود؟ این عمل قابل بازگشت نیست.`)){state.projects=state.projects.filter(x=>x.id!==activeProject);activeProject=null;$('#detail-dialog').close();update();toast('پروژه حذف شد.')}}});
  $('#export-btn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`madar-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('نسخه پشتیبان دریافت شد.')};
  $('#import-btn').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error();const imported=JSON.parse(await file.text());if(!valid(imported))throw Error();if(confirm(`اطلاعات فعلی با ${num(imported.projects.length)} پروژه از فایل جایگزین شود؟ قبل از ادامه از اطلاعات فعلی پشتیبان بگیرید.`)){state=imported;state.projects.forEach(p=>workflow.migrate(p));update();toast('اطلاعات بازیابی شد.')}}catch{toast('فایل پشتیبان معتبر نیست.')}e.target.value=''};
  for(const d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});
  render();
})();
